const translations = {
  en: {
    mainText: "Let's discover potential.",
    mainP: "Come to study abroad to explore your vision.",
    about: "About us",
    vision:"Our Vision",
    mission:"Our Mission",
    aboutT:"Global Group has been providing expert consultancy services in education and international employment across Turkey and Europe since 2018. Since our establishment, we have helped thousands of individuals pursue their dream education and build successful careers abroad. Our goal is to empower students, young professionals, and job seekers to discover their potential and guide them on the right path toward their goals. With a broad network of institutions, trusted partners, and an experienced team of consultants, we offer personalized and strategic solutions tailored to each individual. At Global Group, we are more than just a consultancy firm — we aim to be your partner on this journey. From education planning to job placement, we support you every step of the way with transparency, trust, and professionalism.",
    visionT:"Our vision is to become a leading force in the sector across Turkey and Europe by helping individuals become globally competent, informed, and confident.",
    missionT:"Our mission is to guide our clients in making the right decisions and walking confidently toward a brighter future.",
    partner: "Partner",
    Universities: "Universities",
    residence:"Residence",
    apply:"APPLY",
    How: "How to apply?",
    HowH1: "1. If you want to study in Turkey, you can do it easily.",
    HowH2: "1. You need to click the button above named 'GLOBAL'.",
    HowH3: "2. Then fill out the form and click the 'Send' button.",
    HowH4: "3. Please WAIT. We will call you.",
    HowH5: "4. If we haven't called, you can send an email or SMS.",
    agencyName:"Name of your Agency if you have:",
    adresse:"Adresse: Şirinevler, Gediz Sk. no:10/B, 34134 Bahçelievler/İstanbul",
    all:"ALL",
    approvedUni:"Approved Univeritie",

    cost: "Prices:",
    locationI: "Location: Istanbul.",
    locationAn:"Location: Ankara",
    locationIz:"Location: Izmir",
    locationKon:"Location: Konya",
    locationAnt:"Location: Antalya",
    locationAk:"Location: Aksaray",
    locationE:"Location: Erzurum",
    locationEs:"Location:: Eskishehir",
    locationB:"Location: Bursa",
    locationYo:"Location: Yozgat",
    locationBo:"Location: Bolu",
    locationBil:"Location: Bilecik",
    locationCh:"Location: Chankiri",
    locationAd:"Location:  Adana",
    locationDi:"Location: Diyarbakir",
    locationDu:"Location: Duzce",
    locationKa:"Location: Kaysery",
    locationEl:"Location: Elazig",
    locationKo:"Location: Kocaeli",
    locationKar:"Location: Karabuk",
    locationSak:"Location: Sakarya",
    locationM:"Location: Manisa",


    altinbas:"Altynbash university",
    atilim:"Atylym university.",
    acibadem:"Ajybadem university.",
    akdeniz:"Akdeniz university.",
    aksaray:"Aksaray university.",
    ankara:"Ankara university.",
    ataturk:"Ataturk university.",
    anadolu:"Anadolu university.",
    bahcesehir:"Bahcheshehir university.",
    bartin:"Bartyn university.",
    baskent:"Bashkent university.",
    ayil:"Ankara Yyldyrym Bayezit university.",
    bezmialem:"Bezmialem Vakyf university.",
    bilecik:"Bilejik Sheyh Edebali university.",
    bilkent:"Bilkent university.",
    bogazici:"Bogazichi university.",
    bolu:"Bolu Abant Izzat Baysal university.",
    bozok:"Bozok university.",
    bteknik:"Bursa Technik university.",
    buludag:"Bursa Uludag university.",
    cankaya:"Chankaya university.",
    cankiri:"Chankiri Karatekin university.",
    cukurova:"Chukurova university.",
    dicle:"Dijle university.",
    dokuz:"Dokuz Eylul university.",
    duzce:"Duzje university.",
    ege:"Ege university.",
    erciyes:"Erjiyes university.",
    firat:"Fyrat university.",
    gazi:"Gazi university.",
    gteknik:"Gebze Technik university.",
    hacettepe:"Hajettepe university.",
    bilgi: "Istanbul Bilgi university.",
    medipol:"Istanbul Medipol university.",
    aydin:"Istanbul Aydin university.",
    gelisim:"Istanbul Gelishim university.",
    istinye:"Istinye university.",
    kadir:"Kadir Has university.",
    iyasar:"Izmir Yashar university.",
    medeniyet:"Istanbul culture  university.",
    iteknik:"Istanbul Technik university.",
    istanbul:"Istanbul university.",
    cerrahpasa:"Istanbul university, Jerrahpasha.",
    izteknik:"Izmir high Technik Institude.",
    karabuk:"Karabuk university.",
    koc:"Koch university.",
    manisa:"Manisa Jelal B. university.",
    necmettin:"Nejmeddin E. university.",
    odt:"Orta Dogu Technik university",
    ozyegin:"Ozyegin university.",
    sabanci:"Sabanjy university.",
    sakarya:"Sakarya university.",
    seljuk:"Seljuk university.",
    tobb:"TOBB E. and T. university.",
    yildiz:"Yildiz technik university.",
    sb:"Health Science university.",
  },
  ru: {
    mainText: "Давайте откроем потенциал.",
    mainP: "Приезжайте учиться за границу, чтобы расширить своё видение.",
    about: "О нас",
    vision:"Наше видение",
    mission:"Наша миссия",
    aboutT:"Компания Global Group предоставляет экспертные консалтинговые услуги в сфере образования и международного трудоустройства в Турции и Европе с 2018 года. С момента нашего основания мы помогли тысячам людей получить образование своей мечты и построить успешную карьеру за рубежом. Наша цель — помочь студентам, молодым специалистам и соискателям раскрыть свой потенциал и помочь им найти правильный путь к достижению целей. Благодаря широкой сети учебных заведений, надежным партнерам и опытной команде консультантов мы предлагаем индивидуальные и стратегические решения, разработанные с учетом потребностей каждого. В Global Group мы больше, чем просто консалтинговая компания — мы стремимся стать вашим партнером на этом пути. От планирования образования до трудоустройства мы поддерживаем вас на каждом этапе, обеспечивая прозрачность, доверие и профессионализм.",
    visionT:"Наша цель — стать ведущей силой в этом секторе по всей Турции и Европе, помогая людям стать компетентными, информированными и уверенными в себе на глобальном уровне.",
    missionT:"Наша миссия — помогать нашим клиентам принимать правильные решения и уверенно идти к светлому будущему.",
    partner: "Партнёр",
    Universities: "Университеты",
    residence:"Резиденция",
    apply:"ЗАЯВЛЕНИЕ",
    How: "Как подать заявку?",
    HowH1: "1. Если вы хотите учиться в Турции — это легко.",
    HowH2: "1. Нажмите на кнопку выше с надписью 'GLOBAL'.",
    HowH3: "2. Затем заполните форму и нажмите 'Отправить'.",
    HowH4: "3. Пожалуйста, ЖДИТЕ. Мы вам позвоним.",
    HowH5: "4. Если мы не позвонили — отправьте email или sms.",
    agencyName:"Название вашего агентства, если у вас есть:",
    adresse:"Адрес : Şirinevler, Gediz Sk. no:10/B, 34134 Bahçelievler/İstanbul",
    all:"ВСЕ",
    approvedUni:"Одобренные Универцитеты ",

    cost: "Цены:",
    locationI: "Местоположение: Стамбул",
    locationAn:"Местоположение: Анкара",
    locationIz:"Местоположение: Измир",
    locationKon:"Местоположение: Конья",
    locationAnt:"Местоположение: Анталя",
    locationAk:"Местоположение: Аксрай",
    locationE:"Местоположение: Эрзурум",
    locationEs:"Местоположение: Эскишэхир",
    locationB:"Местоположение: Бурса",
    locationYo:"Местоположение: Ёзгат",
    locationBo:"Местоположение: Болу",
    locationBil:"Местоположение: Биледжик",
    locationCh:"Местоположение: Чанкири",
    locationAd:"Местоположение: Адана",
    locationDi:"Местоположение: Диярбакир",
    locationDu:"Местоположение: Дюздже",
    locationKa:"Местоположение: Кайцеры",
    locationEl:"Местоположение: Элазиг",
    locationKo:"Местоположение: Коджаэли",
    locationKar:"Местоположение: Карабюк",
    locationSak:"Местоположение: Сакаря",
    locationM:"Местоположение: Маниса",

    altinbas:"Унв. Алтынбаш.",
    atilim:"Унв. Атылым.",
    acibadem:"Унв. Аджыбадем.",
    akdeniz:"Унв. Акдениз.",
    aksaray:"Унв. Аксарай.",
    ankara:"Унв. Анкара.",
    ataturk:"Унв. Ататюрк.",
    anadolu:"Унв. Анадолу.",
    bahcesehir:"Унв. Бахчешехир.",
    bartin:"Унв. Бартын.",
    baskent:"Унв. Башкент.",
    ayil:"Унв. Анкара Йилдирим Баезит",
    bezmialem:"Унв. Безмиалем Вакиф.",
    bilecik:"Унв. Биледжик Шейх Эдэбали.",
    bilkent:"Унв. Билкент.",
    bogazici:"Унв. Богазичи.",
    bolu:"Унв. Болу Абант Иззат Байцал.",
    bozok:"Унв. Бозок.",
    bteknik:"Унв. Бурса Текник.",
    buludag:"Унв. Бурса Улудаг.",
    cankaya:"Унв. Чанкайа.",
    cankiri:"Унв. Чанкири Каратекин.",
    cukurova:"Унв. Чукурова.",
    dicle:"Унв. Диджле.",
    dokuz:"Унв. Докуз Эйлюл.",
    duzce:"Унв. Дюздже.",
    ege:"Унв. Эгэ.",
    erciyes:"Унв. Зрджиес.",
    firat:"Унв. Фырать.",
    gazi:"Унв. Гази.",
    gteknik:"Унв. Гебзе Текник.",
    hacettepe:"Унв. Хаджеттепе.",
    bilgi: "Стамбульский унв. Билги.",
    medipol:"Стамбульский унв. Медипол.",
    aydin:"Стамбульский унв. Айдын.",
    gelisim:"Стамбульский унв. Гелишим.",
    istinye:"Унв. Истинье.",
    kadir:"Унв. Кадир Хас.",
    iyasar:"Унв. Измир Яшар.",
    medeniyet:"Стамбулский Унв. Културы.",
    iteknik:"Станбулский Технический Унв.",
    istanbul:"Унв. Станбул.",
    cerrahpasa:"Унв. Станбул, Джеррахпаша.",
    izteknik:"Измирский высший  Технический Институт.",
    karabuk:"Унв. Карабюк.",
    koc:"Унв. Коч.",
    manisa:"Унв. Маниса Джелал Б..",
    necmettin:"Унв. Неджметтин Е..",
    odt:"Унв. Орта Догу Текник.",
    ozyegin:"Унв. Озегин.",
    sabanci:"Унв. Сабанджи.",
    sakarya:"Унв. Сакарья.",
    seljuk:"Унв. Селджук.",
    tobb:"Унв. ТОББ Е. и Т..",
    yildiz:"Унв. Йилдиз Текник.",
    sb:"Унв. Медицинских наук.",
      },
  tr: {
    mainText: "Potansiyeli keşfedelim.",
    mainP: "Vizyonunuzu keşfetmek için yurtdışında okumaya gelin.",
    about: "Hakkımızda",
    vision:"Vizyonumuz",
    mission:"Misyonumuz",
    aboutT:"Global Group, 2018 yılından bu yana Türkiye ve Avrupa genelinde eğitim ve uluslararası istihdam alanlarında uzman danışmanlık hizmetleri sunmaktadır. Kuruluşumuzdan bu yana binlerce kişinin hayalindeki eğitimi almasına ve yurt dışında başarılı kariyerler inşa etmesine yardımcı olduk. Amacımız, öğrencilerin, genç profesyonellerin ve iş arayanların potansiyellerini keşfetmelerine ve hedeflerine doğru yolda ilerlemelerine yardımcı olmaktır. Geniş kurum ağımız, güvenilir ortaklarımız ve deneyimli danışman ekibimizle, her bireye özel, kişiselleştirilmiş ve stratejik çözümler sunuyoruz. Global Group olarak, sıradan bir danışmanlık firmasından çok daha fazlasıyız; bu yolculukta ortağınız olmayı hedefliyoruz. Eğitim planlamasından iş yerleştirmeye kadar, şeffaflık, güven ve profesyonellikle her adımda size destek oluyoruz.",
    visionT:"Vizyonumuz, bireylerin küresel ölçekte yetkin, bilgili ve özgüvenli bireyler haline gelmelerine yardımcı olarak Türkiye ve Avrupa çapında sektörde öncü bir güç olmaktır.",
    missionT:"Misyonumuz, müşterilerimizin doğru kararlar almalarına ve daha parlak bir geleceğe doğru güvenle yürümelerine rehberlik etmektir.",
    partner: "Ortak",
    Universities: "Üniversiteler",
    residence:"Ikamet",
    apply:"BAŞVUR",
    How: "Nasıl başvurulur?",
    HowH1: "1. Türkiye'de okumak istiyorsanız bu çok kolay.",
    HowH2: "1. Yukarıdaki 'GLOBAL' butonuna tıklayın.",
    HowH3: "2. Formu doldurun ve 'Gönder' butonuna tıklayın.",
    HowH4: "3. Lütfen BEKLEYİN. Sizi arayacağız.",
    HowH5: "4. Aramazsak, bize e-posta veya sms gönderin.",
    labelP: "Bölüminizi seçiniz:",
    agencyName:"Eğer varsa, acentenizin adı:",
    adresse:"Adres: Şirinevler, Gediz Sk. no:10/B, 34134 Bahçelievler/İstanbul",
    all:"HEPSI",
    approvedUni:"Onaylanan Üniversitler",

    cost: "Fiyatlar:",
  locationI: "Yer: İstanbul.",
  locationAn:"Yer: Ankara",
  locationIz:"Yer: Izmir",
  locationKon:"Yer: Konya",
  locationAnt:"Yer: Antalya",
  locationAk:"Yer: Aksaray",
  locationE:"Yer: Erzurum",
  locationEs:"Yer: Eskişehir",
  locationB:"Yer: Bursa",
  locationYo:"Yer: Yozgat",
  locationBo:"Yer: Bolu",
  locationBil:"Yer: Bilecik",
  locationCh:"Yer: Çankırı",
  locationAd:"Yer:  Adana",
  locationDi:"Yer: Diyarbakır",
  locationDu:"Yer: Düzce",
  locationKa:"Yer: Kayseri",
  locationEl:"Yer: Elaziğ",
  locationKo:"Yer: Kocaeli",
  locationKar:"Yer: Karabük",
  locationSak:"Yer: Sakarya",
  locationM:"Yer: Manisa",

  altinbas:"Altınbaş Üniversitesi.",
    atilim:"Atılım Üniversitesi.",
    acibadem:"Acıbadem Üniversitesi.",
    akdeniz:"Akdeniz Üniversitesi.",
    aksaray:"Aksaray Üniversitesi.",
    ankara:"Ankara Üniversitesi.",
    ataturk:"Atatürk Üniversitesi.",
    anadolu:"Anadolu Üniversitesi.",
    bahcesehir:"Bahçeşehir Üniversitesi.",
    bartin:" Bartın Üniversitesi.",
    baskent:"Başkent Üniversitesi.",
    ayil:"Ankara Yıldırım Bayezit Üniversitesi.",
    bezmialem:"Bezmialem Vakıf Üniversitesi.",
    bilecik:"Bilecik Şeyh Edebali Üniversitesi.",
    bilkent:"Bilkent Üniversitesi.",
    bogazici:"Boğaziçi Üniversitesi.",
    bolu:"Bolu Abant Izzat Baysal Üniversitesi.",
    bozok:"Bozok Üniversitesi.",
    bteknik:"Bursa Teknik Üniversitesi.",
    buludag:"Bursa Uludağ Üniversitesi.",
    cankaya:"Çankaya Üniversitesi.",
    cankiri:"Çankiri Karatekin Üniversitesi.",
    cukurova:"Çukurova Üniversitesi.",
    dicle:"Dicle Üniversitesi.",
    dokuz:"Dokuz Eylül Üniversitesi.",
    duzce:"Düzce Üniversitesi.",
    ege:"Ege Üniversitesi.",
    erciyes:"Erciyes Üniversitesi.",
    firat:"Fırat Üniversitesi.",
    gazi:"Gazi Üniversitesi.",
    gteknik:"Gebze Teknik Üniversitesi.",
    hacettepe:"Hacettepe Üniversitesi.",
    bilgi: "Istanbul Bilgi Üniversitesi.",
    medipol:"Istanbul Medipol Üniversitesi.",
    aydin:"Istanbul Aydın Üniversitesi.",
    gelisim:"Istanbul Gelişim Üniversitesi.",
    istinye:"Istinye Üniversitesi.",
    kadir:"Kadir Has Üniversitesi.",
    iyasar:"Izmir Yaşar Üniversitesi.",
    medeniyet:"Istanbul Medeniyet  Üniversitesi.",
    iteknik:"Istanbul Teknik Üniversitesi.",
    istanbul:"Istanbul Üniversitesi.",
    cerrahpasa:"Istanbul Üniversitesi, Cerrahpaşa.",
    izteknik:"İzmir Yüksek T. Enstitüsü.",
    karabuk:"Karabük Üniversitesi.",
    koc:"Koç Üniversitesi.",
    manisa:"Manisa Celal B. Üniversitesi.",
    necmettin:"Necmettin E. Üniversitesi.",
    odt:"Orta Doğu Teknik Üniversitesi.",
    ozyegin:"Özyegin Üniversitesi.",
    sabanci:"Sabancı Üniversitesi.",
    sakarya:"Sakarya Üniversitesi.",
    seljuk:"Selçuk Üniversitesi.",
    tobb:"TOBB E. ve T. Üniversitesi.",
    yildiz:"Yildiz teknik Üniversitesi.",
    sb:"Sağlık Bilimler Üniversitesi.",
  
  },
  tu: {
    mainText: "Geliň potensialy açalyň.",
    mainP: "Dünýä garayşyňyzy giňeltmek üçin daşary ýurda okuwa geliň.",
    about: "Biz barada",
    vision:"Görüşimiz",
    mission:"Biziň wezipämiz",
    aboutT:"Global Topar, 2018-nji ýyldan bäri Türkiýe we Ýewropada bilim we halkara iş üpjünçiligi boýunça hünärmenlere maslahat beriş hyzmatlaryny hödürleýär. Döredileli bäri müňlerçe adama  arzuwlaryny dowam etdirmäge we daşary ýurtlarda üstünlikli karýera gurmaga kömek etdik. Biziň maksadymyz, okuwçylara, ýaş hünärmenlere we iş gözleýänlere öz mümkinçiliklerini açmak we maksatlaryna dogry ýolda ugrukdyrmak. Guramalaryň giň ulgamy, ynamdar hyzmatdaşlar we tejribeli geňeşçiler topary bilen, her bir adama laýyklaşdyrylan şahsy we strategiki çözgütleri hödürleýäris. Global Toparda biz diňe bir maslahat beriş firmasy däl, bu syýahatda siziň hyzmatdaşyňyz bolmagy maksat edinýäris. Bilimi meýilleşdirmekden başlap, işe ýerleşmeklige çenli her ädimde aç-açanlyk, ynam we hünär ussatlygy bilen sizi goldaýarys.",
    visionT:"Biziň gözýetimimiz, şahsyýetlere dünýä derejesinde başarnykly,  we ynamly bolmaga kömek etmek bilen Türkiýe we Ýewropa boýunça bu pudakda öňdebaryjy güýç bolmak.",
    missionT:"Biziň wezipämiz, müşderilerimize dogry karar bermekgine komek etmek we olaryň ýagty geljege ynamly ýöremegidir.",
    partner: "Işdeşlik",
    Universities: "Uniwersitetler",
    residence:"Ikamet",
    apply:"ÝÜZ TUTUŇ",
    How: "Nädip ýüz tutmaly?",
    HowH1: "1. Türkiýede okamak isleseňiz bu örän aňsat.",
    HowH2: "1. Ýokardaky 'GLOBAL' düwmesine basyň.",
    HowH3: "2. Formany dolduryň we 'Iber' düwmesine basyň.",
    HowH4: "3. Garaşyň. Biz size jaň ederis.",
    HowH5: "4. Eger biz jaň etmedik bolsak, bize e-poçta ýa-da sms iberiň.",
    labelP: "Bölümıňizi saýlaň:",
    agencyName:"Agentligiňiziň ady, eger bar bolsa:",
    adresse:"Salgymyz: Şirinevler, Gediz Sk. no:10/B, 34134 Bahçelievler/İstanbul",
    all:"HEMMESI",
    approvedUni:"Tassyklanýan Üniwersitetler",

    cost: "Bahalar:",
    locationI: "Yeri: İstanbul.",
    locationAn:"Yeri: Ankara",
    locationIz:"Yeri: Izmir",
  locationKon:"Yeri: Konýa",
  locationAnt:"Yeri: Antalýa",
  locationAk:"Yeri: Aksaraý",
  locationE:"Yeri: Erzurum",
  locationEs:"Yeri: Eskişehir",
  locationB:"Yeri: Bursa",
  locationYo:"Yeri: Ýozgat",
  locationBo:"Yeri: Bolu",
  locationBil:"Yeri: Bilejik",
  locationCh:"Yeri: Çankyry",
  locationAd:"Yeri:  Adana",
  locationDi:"Yeri: Diýarbekir",
  locationDu:"Yeri: Düzje",
  locationKa:"Yeri: Kaýseri",
  locationEl:"Yeri: Elazig",
  locationKo:"Yeri: Kojaeli",
  locationKar:"Yeri: Karabük",
  locationSak:"Yeri: Sakarýa",
  locationM:"Yeri: Manisa",


  altinbas:"Altynbaş Üniwersiteti.",
  atilim:"Atylym Üniwersiteti.",
  acibadem:"Ajybadem Üniwersiteti.",
  akdeniz:"Akdeňiz Üniwersiteti.",
  aksaray:"Aksaraý Üniwersiteti.",
  ankara:"Ankara Üniwersiteti.",
  ataturk:"Atatürk Üniwersiteti.",
  anadolu:"Anadoly Üniwersiteti.",
  bahcesehir:"Bahçeşehir Üniwersiteti.",
  bartin:" Bartyn Üniwersiteti.",
  baskent:"Başkent Üniwersiteti.",
  ayil:"Ankara Yyldyrym Baýezid Üniwersiteti.",
  bezmialem:"Bezmialem Vakyf Üniwersiteti.",
  bilecik:"Bilejik Şeyh Edebali Üniwersiteti.",
  bilkent:"Bilkent Üniwersiteti.",
  bogazici:"Bogaziçi Üniwersiteti.",
  bolu:"Bolu Abant Izzat Baýsal Üniwersiteti.",
  bozok:"Bozok Üniwersiteti.",
  bteknik:"Bursa Tehnik Üniwersiteti.",
  buludag:"Bursa Uludag Üniwersiteti.",
  cankaya:"Çankaya Üniwersiteti.",
  cankiri:"Çankiri Karatekin Üniwersiteti.",
  cukurova:"Çukuroba Üniwersiteti.",
  dicle:"Dijle Üniwersiteti.",
  dokuz:"Dokuz Eýlül Üniwersiteti.",
  duzce:"Düzje Üniwersiteti.",
  ege:"Ege Üniwersiteti.",
  erciyes:"Erjiyes Üniwersiteti.",
  firat:"Fyrat Üniwersiteti.",
  gazi:"Gazy Üniwersiteti.",
  gteknik:"Gebze Tehnik Üniwersiteti.",
  hacettepe:"Hajettepe Üniwersiteti.",
  bilgi: "Istanbul Bilgi Üniwersiteti.",
  medipol:"Istanbul Medipol Üniwersiteti.",
  aydin:"Istanbul Aydyň Üniwersiteti.",
  gelisim:"Istanbul Gelişim Üniwersiteti.",
  istinye:"Istinýe Üniwersiteti.",
  kadir:"Kadir Has Üniwersiteti.",
  iyasar:"Izmir Ýaşar Üniwersiteti.",
  medeniyet:"Istanbul Medeniýet Üniwersiteti.",
  iteknik:"Istanbul Tehnik Üniwersiteti.",
  istanbul:"Istanbul Üniwersiteti.",
  cerrahpasa:"Istanbul Üniwersiteti, Jerrahpaşa.",
  izteknik:"Izmir Ýokary Tehnik Institudy.",
  karabuk:"Karabük Üniwersiteti.",
  koc:"Koç Üniwersiteti.",
  manisa:"Manisa Jelal B. Üniwersiteti.",
  necmettin:"Nejmeddin E. Üniwersiteti.",
  odt:"Orta Dogu Tehnik Üniwersiteti.",
  ozyegin:"Özýegin Üniwersiteti.",
  sabanci:"Sabanjy Üniwersiteti.",
  sakarya:"Sakarýa Üniwersiteti.",
  seljuk:"Seljuk Üniwersiteti.",
  tobb:"TOBB E. ve T. Üniwersiteti.",
  yildiz:"Yyldyz tehnik Üniwersiteti.",
  sb:"Saglyk Bilimler Üniwersiteti.",

  }
};

const switcher = document.getElementById("langs");
const currentLang = localStorage.getItem("lang") || "en";

// ✅ Предотврати ошибку, если язык не существует
if (!translations[currentLang]) {
  localStorage.setItem("lang", "en");
}

switcher.value = currentLang;
applyLanguage(currentLang);

switcher.addEventListener("change", () => {
  const lang = switcher.value;
  if (!translations[lang]) return;
  localStorage.setItem("lang", lang);
  applyLanguage(lang);
});

function applyLanguage(lang) {
  if (!translations[lang]) return; // 🔐 Безопасность

  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.getAttribute("data-i18n");
    const translation = translations[lang][key];
    if (translation) {
      el.textContent = translation;
    }
  });
}


let radioMentor=document.getElementById("radio1").value;
const radioAgency=document.getElementById("radio2").value;
let label=document.getElementById("labelP");

if(radioMentor.onclick){
  label.textContent=`Name and Surname`;
}else{
  label.textContent=`Name of Agency`;
}

